### ISSUE TITLE
Need Help in importing the disqus comments

### ISSUE THREAD

**Issue by lavkumarv** [coralproject/talk-importer#6]
Hi,

I have comments and user info in the XML file and I want to import it to talk. But I few doubts regarding this.

1. What should there in .env file?
2. Does it except XML file? Will a single XML file containing all data (user, comments) will work?
3. What is the difference between two strategies?

**Comment by kgardnr** [comment]
Hey @lavkumarv!

This iteration of the importer doesn't support Disqus as it is, but it would be straightforward to add. Is your export file XML? How many comments are you exporting?

Re: .env file - do you have a Talk install you'll be migrating to? If not, you should set that up. The .env file will be the required configuration for that Talk install - see more here: https://docs.coralproject.net/talk/configuration/
